version: "3.9"
services:
  mysql:
    image: "mysql:latest"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - /var/lib/mysql/
    ports:
      - "6603:6603"
  backend:
    #image: "wrnkt/scpbackend:latest"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql
