name: Nightly Feature Auto Merge
on: 
  schedule:
    - cron: "*/5 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
          repository: wrnkt/starcircleplus
          token: ${{ github.token }}
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge service back to dev
      run: |
          git merge --no-ff main spring-services
          git checkout main
          git commit -m "Auto-merge spring-services into main"
          git push
    - name: Merge service back to dev
      run: |
          git merge --no-ff main react-native-ios
          git checkout main
          git commit -m "Auto-merge react-native-ios into main"
          git push
