name: Nightly Feature Auto Merge
on: 
  schedule:
    - cron: "0 8 * * *"
  
jobs:
  testservice:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: spring-services
          #fetch-depth: 0
          token: ${{ secrets.GH_BOT_PAT }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - name: Run tests
        run: |
          mvn -f service/starcircleplus/ test

  automergereact:
    name: Merge iOS React feature branch into main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_BOT_PAT }}
    - name: Set config values
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge react-native-ios into main
      run: |
        git checkout main
        git merge --no-ff origin/react-native-ios
        git diff-index --quiet --cached HEAD || { git commit -m "Auto-merge react-native-ios into main"; }
        git push

  automergeservice:
    name: Merge Spring Web service feature branch into main
    needs: testservice
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_BOT_PAT }}
    - name: Set config values
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge spring-services into main
      run: |
        git checkout main
        git merge --no-ff origin/spring-services
        git diff-index --quiet --cached HEAD || { git commit -m "Auto-merge spring-services into main"; }
        git push



      
