name: Nightly Feature Auto Merge
on: 
  schedule:
    - cron: "24 0 * * *"
jobs:
  merge-service-back-to-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge service back to dev
      run: |
          git merge --no-ff main spring-services
          git checkout main
          git commit -m "Auto-merge spring-services into main"
          git push
  merge-iosfrontend-back-to-main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge service back to dev
      run: |
          git merge --no-ff main react-native-ios
          git checkout main
          git commit -m "Auto-merge react-native-ios into main"
          git push
