name: Nightly Feature Auto Merge
on: 
  schedule:
    - cron: "0 8 * * *"
jobs:
  automerge:
    name: Merge features into main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_BOT_PAT }}
    - name: Set config values
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: List Branches
      run: |
          git branch -a

    - name: Merge react-native-ios into main
      run: |
        git checkout main
        git merge --no-ff origin/react-native-ios
        git diff-index --quiet --cached HEAD || { git commit -m "Auto-merge react-native-ios into main"; }
        git push
    - name: Merge spring-services into main
      run: |
        git checkout main
        git merge --no-ff origin/spring-services
        git diff-index --quiet --cached HEAD || { git commit -m "Auto-merge spring-services into main"; }
        git push
      
