name: Feature Test & Auto Merge

on: 
  schedule:
    - cron: "0 8 * * *" # 4AM EST
  workflow_call:
  workflow_dispatch:
    #inputs:
      #logLevel:
      #  description: 'Log level'     
      #  required: true
      #  default: 'warning'
      #tags:
      #  description: 'Test scenario tags'  
  
jobs:
  testservice:
    name: Test service branch
    uses: ./.github/workflows/testbranch.yml
    secrets: inherit
    with:
      branch: spring-services

  mergeservice:
    name: Merge Spring Web service feature branch into main
    needs: testservice
    uses: ./.github/workflows/mergebranch.yml
    secrets: inherit
    with:
      source: spring-services
      destination: main

  mergereact:
    name: Merge iOS React feature branch into main
    needs: [testservice, mergeservice]
    uses: ./.github/workflows/mergebranch.yml
    secrets: inherit
    with:
      source: react-native-ios
      destination: main
