on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        token: ${{ secrets.GH_BOT_PAT }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: 'maven'
    - name: Run tests
      run: |
        mvn -f service/starcircleplus/ test
