name: Update Feature Branches

on:
  workflow_dispatch:

jobs:
  testmain:
    name: Test main branch
    uses: ./.github/workflows/testbranch.yml
    secrets: inherit
    with:
      branch: main

  updateservice:
    name: Pull main into spring-services
    needs: testmain
    uses: ./.github/workflows/updatebranch.yml
    secrets: inherit
    with:
      source: main
      destination: spring-services

  updatereact:
    name: Pull main into react-native-ios
    needs: testmain
    uses: ./.github/workflows/updatebranch.yml
    secrets: inherit
    with:
      source: main
      destination: react-native-ios
