name: Pull main into feature branches

on:
  workflow_dispatch:

jobs:
  testmain:
    name: Test main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
          #fetch-depth: 0
          token: ${{ secrets.GH_BOT_PAT }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - name: Run tests
        run: |
          mvn -f service/starcircleplus/ test

  updateservice:
    name: Pull main into spring-services
    needs: testmain
    uses: ./.github/workflows/updatebranch.yml
    secrets: inherit
    with:
      source: main
      destination: spring-services

  updatereact:
    name: Pull main into react-native-ios
    runs-on: ubuntu-latest
    needs: testmain
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_BOT_PAT }}
    - name: Set config values
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Pull main into react-native-ios
      run: |
        git checkout spring-services
        git pull origin main
        git diff-index --quiet --cached HEAD || { git commit -m "Auto-pull main into spring-services"; }
        git push
